name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-host:
    name: Swift Build (Host)
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel, ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install swiftly
      run: |
        case "$RUNNER_OS" in
          macOS)
            curl -L https://download.swift.org/swiftly/darwin/swiftly.pkg > swiftly.pkg
            installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
            ~/.swiftly/bin/swiftly init -y --skip-install
            . "$HOME/.swiftly/env.sh"
            ;;
          Linux)
            sudo apt-get update
            sudo apt-get install -y libcurl4-openssl-dev
            if [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
              sudo apt-get install -y pkg-config python3-lldb-13
            fi
            curl -L https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz > swiftly.tar.gz
            tar zxf swiftly.tar.gz
            ./swiftly init -y --skip-install
            . "$HOME/.local/share/swiftly/env.sh"
            ;;
          *)
            echo "Unsupported OS: $RUNNER_OS"
            exit 1
            ;;
        esac
        echo "$(dirname $(which swiftly))" >> $GITHUB_PATH
    - uses: actions/checkout@v6
    - name: Install the toolchain
      run: swiftly install -u -y
    - name: Show Swift Version
      run: swift --version
    - name: Build
      run: swift build -v

  prepare-for-container:
    name: Prepare Environment for Container
    runs-on: ubuntu-slim
    outputs:
      swift_version: ${{ steps.read_version.outputs.version }}
    steps:
    - uses: actions/checkout@v6
    - name: Read .swift-version
      id: read_version
      run: |
        VERSION=$(cat .swift-version | xargs)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-container:
    name: Swift Build (Container)
    needs: prepare-for-container
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          tag: noble
          workspace: /workspace
        - os: ubuntu-latest
          tag: jammy
          workspace: /workspace
        - os: ubuntu-latest
          tag: bookworm
          workspace: /workspace
        - os: ubuntu-latest
          tag: amazonlinux2
          workspace: /workspace
        - os: ubuntu-latest
          tag: rhel-ubi9
          workspace: /workspace
        - os: windows-2025
          tag: windowsservercore-ltsc2022
          workspace: C:\workspace
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Show Swift Version
      run: |
        docker run --rm swift:${{ needs.prepare-for-container.outputs.swift_version }}-${{ matrix.tag }} swift --version
    - name: Build
      run: |
        docker run --rm -v "${{ github.workspace }}:${{ matrix.workspace }}" -w "${{ matrix.workspace }}" swift:${{ needs.prepare-for-container.outputs.swift_version }}-${{ matrix.tag }} swift build -v
