name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift Build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: swift build -v
